//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp24TodoEF6
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public System.DateTime Deadline { get; set; }
    }
}
